debug: true
server:
  port: 8088
  #servlet:
      #context-path: /OnlineCodeEditingTool
spring:
       #profiles: dev
    mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp
    static-path-pattern: /**
    resources:
             static-locations: classpath:/META-INF/resources/
    datasource:
            name: oracle
            # 如果存在多个数据源，监控的时候可以通过名字来区分开来
            # 连接数据库的url
            url: jdbc:oracle:thin:@localhost:1521:orcl
            #url: jdbc:mysql://132.232.240.177:3306/qrcode?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
            #url: jdbc:mysql://129.28.109.71:3306/qrcode?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
            # 连接数据库的账号
            username: pbms
            #  连接数据库的密码
            #yn_odr520!
            password: pbms
            #Oracle驱动
            driver-class-name: oracle.jdbc.driver.OracleDriver
            #mysql驱动
            #driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  # pojo生成包地址
  type-aliases-package: com.cn.wordonlineediting.entity

#log4j2
logging:
  config: classpath:log4j2-spring.xml
  # 打印sql
  level:
       com.cn.wordonlineediting.dao: debug

  # pagehelper分页插件
pagehelper:
      # 数据库的方言
      helperDialect: mysql
      # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
      reasonable: true
      offsetAsPageNum: true
      rowBoundsWithCount: true


#应用配置
resources:
    # log文件写入地址
    logdir: log/
    # 应用名称
    appname: spring-boot-example
    # 日志打印的基础扫描包
    basepackage: com.cn.wordonlineediting
#添加Swagger配置

#对swagger-ui进行配置
#pringfox:
  #documentation:
    #swagger:
      #v2:
        #host: 129.28.109.71:8888/anscodeApi